### PR TITLE
Fixes and release

### PR DESCRIPTION
**Pull request by JuiP**
- [x] The activity process kept running even after clicking on the stop button. Fixed in 2a7e978
- [x] PyGIWarnings fixed
- [x] Release new version

@quozl @chimosky please test and review changes till 403e47c. So I can push release related changes

### CODE REVIEW

**Comment by quozl** [comment]
Re: 403e47c.  It is better to move the existing `gi.require_version` check higher in the source file it occurs in, or import Main later.

**Comment by JuiP** [comment]
These activity versions are not uploaded on https://activities.sugarlabs.org/en-US/sugar/search?q=clock&cat=all.
The method of download I mentioned in the README is download from GitHub. Is there any way to upload this activity on https://activities.sugarlabs.org ?

Also, I feel why not include this activity as a part of sugar? Like a similar implememntation of Analyze Journal to dashboard?
@quozl @chimosky @srevinsaju

**Comment by quozl** [comment]
[Clock](https://github.com/sugarlabs/clock-activity) is often used instead.

JAMclock was written for a specific country school system.  JAMclock was available on activities.laptop.org as [node 4508](https://github.com/sugar-activities/4508-activity) but has been deleted, possibly by the original maintainer.  The repository here was uploaded by someone other than the original maintainer.  activities.sugarlabs.org at the moment can't host Python 3 activities because it has no concept of the Python 2 to Python 3 transition, and loading a Python 3 activity to those old laptops in the field will break the activity, with the child usually unable to recover an older version.  With the older version missing from activities.sugarlabs.org, it is even more important not to release a Python 3 version there.  @srevinsaju has been working on a replacement for activities.sugarlabs.org which may have some way to detect which versions of Python are supported by the toolkit.  It is a complicated thing; JavaScript on a web page has to have a way to query the Browse activity to introspect the Sugar Toolkit without executing it.

**Comment by quozl** [comment]
Thanks.  Reviewed.  Approved.

**Comment by chimosky** [comment]
Reviewed, thanks.

**Pull request merged**
